# Deployment groups
- id: primary-lcm
  type: group
  role: [primary-lcm]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: [hiera, fuel_pkgs, globals, tools, logging, netconfig,
          hosts, firewall, deploy_start, mariadb_galera, nsm, keepalived,
          lcm_haproxy, puppet_master, foreman_main]
  parameters:
    strategy:
      type: one_by_one

- id: lcm
  type: group
  role: [lcm]
  requires: [deploy_start, primary-lcm]
  required_for: [deploy_end]
  tasks: [hiera, fuel_pkgs, globals, tools, logging, netconfig,
          hosts, firewall, deploy_start, mariadb_galera, nsm, keepalived,
          lcm_haproxy, puppet_master, foreman_main]
  parameters:
    strategy:
      type: one_by_one

# Deployment tasks
- id: mariadb_galera
  type: puppet
  role: [primary-lcm, lcm]
  required_for: [deploy_end]
  requires: [hosts]
  parameters:
    puppet_manifest: puppet/manifests/database.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: nsm
  type: puppet
  role: [primary-lcm, lcm]
  required_for: [deploy_end]
  requires: [hosts]
  parameters:
    puppet_manifest: puppet/modules/plugin_lcm/manifests/nsm.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: keepalived
  type: puppet
  role: [primary-lcm, lcm]
  required_for: [deploy_end]
  requires: [hosts]
  parameters:
    puppet_manifest: puppet/modules/plugin_lcm/manifests/keepalived.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: lcm_haproxy
  type: puppet
  role: [primary-lcm, lcm]
  required_for: [deploy_end]
  requires: [hosts]
  parameters:
    puppet_manifest: puppet/manifests/haproxy.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: puppet_master
  type: puppet
  role: [primary-lcm, lcm]
  required_for: [deploy_end]
  requires: [hosts]
  parameters:
    puppet_manifest: puppet/manifests/puppet_master.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: puppet_agent_pre
  type: shell
  role: '*'
  required_for: [pre_deployment_start]
  parameters:
    cmd: if [ -f /etc/init.d/puppet ]; then service puppet stop; fi
    retries: 3
    interval: 20
    timeout: 180


- id: puppet_agent_post
  type: shell
  role: '*'
  requires: [post_deployment_end]
  parameters:
    cmd: service puppet start
    retries: 3
    interval: 20
    timeout: 180

- id: foreman_main
  type: puppet
  role: [primary-lcm, lcm]
  required_for: [deploy_end]
  requires: [puppet_master,mariadb_galera]
  parameters:
    puppet_manifest: puppet/manifests/foreman_main.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600


