# Deployment groups
- id: primary-lcm
  type: group
  role: [primary-lcm]
  required_for: [deploy_end]
  requires: [deploy_start]
  tasks: &common_tasks
    - hiera
    - setup_repositories
    - fuel_pkgs
    - globals
    - tools
    - logging
    - netconfig
    - hosts
    - firewall
  parameters:
    strategy:
      type: one_by_one

- id: lcm
  type: group
  role: [lcm]
  required_for: [deploy_end]
  requires: [deploy_start, primary-lcm]
  tasks: *common_tasks
  parameters:
    strategy:
      type: parallel

# Deployment tasks
- id: mariadb_galera
  type: puppet
  groups: &lcm_nodes
    - lcm
    - primary-lcm
  required_for: [deploy_end]
  requires: [netconfig]
  parameters:
    puppet_manifest: puppet/manifests/database.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: nsm
  type: puppet
  groups: *lcm_nodes
  required_for: [deploy_end]
  requires: [netconfig]
  parameters:
    puppet_manifest: puppet/manifests/nsm.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: keepalived
  type: puppet
  groups: *lcm_nodes
  required_for: [deploy_end]
  requires: [netconfig]
  parameters:
    puppet_manifest: puppet/manifests/keepalived.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: haproxy
  type: puppet
  groups: *lcm_nodes
  required_for: [deploy_end]
  requires: [netconfig]
  parameters:
    puppet_manifest: puppet/manifests/haproxy.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: puppet_master
  type: puppet
  groups: [primary-lcm, lcm]
  required_for: [deploy_end]
  requires: [hiera]
  parameters:
    puppet_manifest: puppet/manifests/puppet_master.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: puppet_agent_pre
  type: shell
  role: '*'
  required_for: [pre_deployment_start]
  parameters:
    cmd: if [ -f /etc/init.d/puppet ]; then service puppet stop; fi
    retries: 3
    interval: 20
    timeout: 180

- id: puppet_agent_post
  type: shell
  role: '*'
  requires: [post_deployment_end]
  parameters:
    cmd: service puppet start
    retries: 3
    interval: 20
    timeout: 180

- id: r10k_deploy
  type: puppet
  groups: *lcm_nodes
  required_for: [deploy_end]
  requires: [hosts]
  parameters:
    puppet_manifest: puppet/manifests/r10k_deploy.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: r10k_init
  type: puppet
  groups: *lcm_nodes
  required_for: [deploy_end]
  requires: [r10k_deploy]
  parameters:
    puppet_manifest: puppet/manifests/r10k_init.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: r10k_webhook
  type: puppet
  groups: *lcm_nodes
  required_for: [deploy_end]
  requires: [puppet_master]
  parameters:
    puppet_manifest: puppet/manifests/r10k_webhook.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600


- id: hiera_apache
  type: puppet
  groups: *lcm_nodes
  required_for: [foreman_main]
  requires: [puppet_master,mariadb_galera]
  parameters:
    puppet_manifest: puppet/manifests/hiera_apache.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: foreman_main
  type: puppet
  groups: *lcm_nodes
  required_for: [hiera_apache_rm]
  requires: [hiera_apache]
  parameters:
    puppet_manifest: puppet/manifests/foreman_main.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600


- id: hiera_apache_rm
  type: puppet
  groups: *lcm_nodes
  required_for: [deploy_end]
  requires: [foreman_main]
  parameters:
    puppet_manifest: puppet/manifests/hiera_apache_rm.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

