attributes:
  metadata:
    mariadb_root_password:
      generator: "password"
    mariadb_check_password:
      generator: "password"

# HAProxy
  ha_puppet_options:
    description: "The options for haproxy of service Puppet Master"
    label: "Puppet HA options"
    type: "text"
    value: "tcpka"
    weight: 50
  ha_mariadb_options:
    description: "The options for haproxy of service Mariadb"
    label: "Mariadb HA options"
    type: "text"
    value: "'tcplog', 'clitcpka', 'srvtcpka'"
    weight: 60
  lcm_ha_foreman_443_options:
    description: "The options for haproxy of service Foreman on 443"
    label: "Foreman on 443 HA options"
    type: "text"
    value: "'httplog', 'httpclose'"
    weight: 70
  lcm_ha_foreman_8443_options:
    description: "The options for haproxy of service Foreman on 8443"
    label: "Foreman on 8443 HA options"
    type: "text"
    value: "'httplog', 'httpclose'"
    weight: 72
  lcm_ha_foreman_80_options:
    description: "The options for haproxy of service Foreman on 80"
    label: "Foreman on 80 HA options"
    type: "text"
    value: "'httplog', 'httpclose'"
    weight: 74
  lcm_ha_middleware_options:
    description: "The options for haproxy of service Middleware"
    label: "Middleware HA options"
    type: "text"
    value: "'httplog', 'httpclose'"
    weight: 80

# Keepalived
  keepalived_cidr:
    value: '10.255.0.0/16'
    label: 'Keepalived CIDR'
    description: 'The CIDR for keepalived daemons. It would be bridged into management network and must not interfere with management CIDR'
    weight: 30
    type: "text"
    regex:
      source: '^(?:(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\/([1-9]|[1-2]\d|3[0-2])$'
      error: "Invalid CIDR"
  public_vip_enabled:
    description: "Enable public vip reservation for LCM webui"
    label: "Enable public vip reservation for LCM webui"
    type: "checkbox"
    value: false
    weight: 32


########################## Fuel Puppetmaster plugin params:   https://gist.github.com/sbrimhall/79997bd90c7e5eca9e2f   ###########################################
#foreman:
  foreman_user:
    value: 'admin'
    label: 'Foreman username'
    type: "text"
    description:
    weight: 510
    regex:
      source: &letdig_regex '^[A-Za-z0-9]*$'
      error: "Valid option is a sequence of letters and digits"

  foreman_password:
    value: 'changeme'
    label: 'Foreman password'
    type: "text"
    description:
    weight: 520
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters"

  deploy_user:
    value: 'deploy_user'
    label: 'Operator username'
    type: "text"
    description:
    weight: 530
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and underscore"
    restrictions:
      - condition: "true" 
        action: "disable"

  deploy_password:
    value: 'deploy_password'
    label: 'Operator password'
    type: "text"
    description:
    weight: 540
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"
    restrictions:
      - condition: "true" 
        action: "disable"

  oauth_consumer_key:
    value: 'WvZpMupBEGZPj6RXXZBprvUKg6kSNM5e'
    label: 'Oauth consumer key'
    type: "text"
    description: |
      Oauth key and secret values fom your Foreman instance
      You can retrieve them later from
      Foreman Administer > Settings > Auth
    weight: 550
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"

  oauth_consumer_secret:
    value: 'EiwMYSN78wKxQETrqB7rhCWBn9HcXV3x'
    label: 'Oauth consumer secret'
    type: "text"
    description:
    weight: 560
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"

  own_ssl_certificate: # Checkbox
    description:
    label: "Use custom certificates on LCM nodes."
    type: "checkbox"
    value: false
    weight: 565

  ssl_ca_location:
    value: "" 
    label: "SSL CA location"
    type: "text"
    description: |
      Provide path to custom SSL CA. 
      Ex: /var/lib/puppet/ssl/certs/ca.pem
    weight: 570
    restrictions:
      - condition: "settings:fuel-plugin-lcm.own_ssl_certificate.value != true"
        action: "disable"
    regex:
      source: &file_path '^(/[-A-Za-z0-9_./]*|^)$'
      error: "Non valid option. Wrong symbol."

  ssl_cert_location:
    value: ""
    label: "SSL CERT location"
    type: "text"
    description: |
      Provide path to custom SSL CERT. 
      Ex: /var/lib/puppet/ssl/certs/fuel.domain.tld.pem
    weight: 580
    restrictions:
      - condition: "settings:fuel-plugin-lcm.own_ssl_certificate.value != true"
        action: "disable"
    regex:
      source: *file_path
      error: "Non valid option. Wrong symbol."

  ssl_crl_location:
    value: ""
    label: "SSL CRL location"
    type: "text"
    description: | 
      Provide path to custom SSL CRL. 
      Ex.: /var/lib/puppet/ssl/crl.pem
    weight: 590
    restrictions:
      - condition: "settings:fuel-plugin-lcm.own_ssl_certificate.value != true"
        action: "disable"
    regex:
      source: *file_path
      error: "Non valid option. Wrong symbol."


  db_user:
    value: 'foreman'
    label: "DB username"
    type: "text"
    description: "Database 'production' user"
    weight: 600
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters"

  db_pass:
    value: 'changeme' 
    label: "DB password"
    type: "text"
    description: "Database 'production' password"
    weight: 610
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters"

  own_puppet_certificate: # Checkbox
    description:
    label: "Use custom puppet certificates on LCM nodes."
    type: "checkbox"
    value: false
    weight: 650

  puppet_ssl_ca_location:
    value: ''
    label: "Puppet ssl ca location"
    type: "text"
    description: |
      Provide path to custom SSL CA. 
      Ex: /var/lib/puppet/ssl/certs/ca.pem
    weight: 660
    restrictions:
      - condition: "settings:fuel-plugin-lcm.own_puppet_certificate.value != true"
        action: "disable"
    regex:
      source: *file_path
      error: "Non valid option. Wrong symbol."

  puppet_ssl_cert:
    value: ''
    label: "Puppet ssl cert"
    type: "text"
    description: |
      Provide path to custom SSL CERT. 
      Ex: /var/lib/puppet/ssl/certs/fuel.domain.tld.pem
    weight: 670
    restrictions:
      - condition: "settings:fuel-plugin-lcm.own_puppet_certificate.value != true"
        action: "disable"
    regex:
      source: *file_path
      error: "Non valid option. Wrong symbol."

  puppet_ssl_key:
    value: ''
    label: "Puppet ssl key"
    type: "text"
    description: |
      Provide path to custom SSL KEY. 
      Ex: /var/lib/puppet/ssl/private_keys/fuel.domain.tld.pem
    weight: 680
    restrictions:
      - condition: "settings:fuel-plugin-lcm.own_puppet_certificate.value != true"
        action: "disable"
    regex:
      source:  *file_path
      error: "Non valid option. Wrong symbol."

  foreman_base_url:
    value: 'localhost'
    label: "Foreman base url"
    type: "text"
    description: |
      Smart proxy needs to know
      where Foreman API lives
    weight: 690
    regex:
      source:  '^[-A-Za-z0-9_:./]*$' 
      error: "Non valid option. Wrong symbol."

  oauth_effective_user:
    value: 'admin'
    label: "Oauth effective user"
    type: "text"
    description: "User to be used for REST interaction"
    weight: 700
    regex:
      source: '^[A-Za-z0-9]*$'
      error: "Valid option is a sequence of letters and digits"

  tftp:  # (boolean to turn on tftp or not)
    description:  
    label: "Use foreman TFTP"
    type: "checkbox"
    value: false
    weight: 720
  dhcp:  # (boolean for dhcp)
    description: 
    label: "Use foreman DHCP"
    type: "checkbox"
    value: false
    weight: 730
  dns:   # (boolean for dns)
    description: 
    label: "Use foreman DNS"
    type: "checkbox"
    value: false
    weight: 740
  bmc:   # (boolean for IPMI plugin)
    description: 
    label: "Use foreman IPMI plugin"
    type: "checkbox"
    value: false
    weight: 750

