attributes:
  metadata:
    mariadb_root_password:
      generator: "password"
    mariadb_check_password:
      generator: "password"
    keepalived_psk:
      generator: "password"

# Keepalived
  keepalived_cidr:
    value: '10.255.0.0/16'
    label: 'Keepalived CIDR'
    description: 'The CIDR for keepalived daemons. It would be bridged into management network and must not interfere with management CIDR'
    weight: 30
    type: "text"
    regex:
      source: '^(?:(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\/([1-9]|[1-2]\d|3[0-2])$'
      error: "Invalid CIDR"

  keepalived_vrid:
    value: '50'
    label: 'Keepalived virtual router id'
    description: 'Virtual router id for LCM keepalived instace'
    weight: 35
    type: "text"
    regex:
      source: '^([1-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-4])$'
      error: "Invalid VRID. Value should be in range between 1 and 254"
  public_vip_enabled:
    description: "Enable public vip reservation for LCM webui"
    label: "Enable public VIP"
    type: "checkbox"
    value: false
    weight: 40

# Puppet Master
  puppetmaster:
    label: "Puppet master FQDN"
    description: "Puppet master FQDN. If not set - VIP will be used"
    type: "text"
    regex:
      source: &fqdn_regex '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$|^$'
      error: "Invalid Puppet master FQDN"
    value: ""
    weight: 95
  ca_server:
    label: "CA server FQDN"
    description: "Certification Authority server"
    type: "text"
    regex:
      source: *fqdn_regex
      error: "Invalid CA server FQDN"
    value: ""
    weight: 100
  dns_alt_names:
    label: "Alternate names for Puppet master"
    description: "Comma separated alternate DNS names to allow to be valid for a certification. Example: host,host.smth.com"
    type: "text"
    regex:
      source: '^(((([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]))+)(,((([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]))+)*$|^$'
      error: "Invalid DNS names"
    value: ""
    weight: 110
  server_foreman_url:
    label: "Foreman URL"
    description: "Custom URL for the Foreman installation. By default used Puppet master FQDN. Example: https://foreman.com"
    type: "text"
    regex:
      source: &url_regex '^(?:[hH][tT][tT][pP](?:[sS])?:\/\/)(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$|^$'
      error: "Invalid URL"
    value: ""
    weight: 120

# R10k:
  private_repo:
    description: "Switch ON if R10k control repo is private."
    label: "Configure private repo user"
    type: "checkbox"
    value: false
    weight: 125
  r10k_do_init:
    description: "If r10k should create puppet env after deployment"
    label: "Create puppet env"
    type: "checkbox"
    value: false
    weight: 130
  r10k_branch:
    description: "Branch name to be used for puppet env creation"
    label: "Branch name"
    type: "text"
    value: 'master'
    weight: 135
    restrictions:
      - condition: "settings:fuel-plugin-lcm.r10k_do_init.value != true"
        action: hide
  r10k_key:
    description: "Please supply private key for R10k to access a private repo by SSH."
    label: "Private key for a private repo"
    type: "file"
    value: ''
    weight: 140
    restrictions:
      - condition: "settings:fuel-plugin-lcm.private_repo.value != true"
        action: hide
  user:
    description: "Please supply R10k username for private repo"
    label: "R10k username"
    type: "text"
    value: "puppetr10k"
    weight: 145
    restrictions:
      - condition: "settings:fuel-plugin-lcm.private_repo.value != true"
        action: hide
  mode:
    description: "Please supply mode for R10k files"
    label: "R10k privileges mode"
    type: "text"
    value: "0755"
    weight: 150
    restrictions:
      - condition: "settings:fuel-plugin-lcm.private_repo.value != true"
        action: hide
  remote_repo:
    description: "Please supply control repo link for R10k"
    label: "R10k control repo link"
    type: "text"
    value: ''
    weight: 155

# R10k Webhook:
  default_vhost:
    label: "Enable default vhost for Apache frontend"
    type: "checkbox"
    value: true
    weight: 160
  port:
    description: "Please supply port number for Middlware"
    label: "Middleware Http port"
    type: "text"
    value: "9292"
    weight: 165
  webhook_auth_user:
    description: "Please provide a priviledged user name"
    label: "Priviledged user account"
    type: "text"
    value: "root"
    weight: 170
  webhook_private_key:
    description: "Please supply a private key for R10k user SSH authorization"
    label: "r10k private key"
    type: "file"
    value: ''
    weight: 175
  webhook_public_key:
    description: "Please supply a public key for R10k user SSH authorization"
    label: "r10k public key"
    type: "file"
    value: ''
    weight: 180

  ##### Source document from Scott:  https://gist.github.com/sbrimhall/79997bd90c7e5eca9e2f
  foreman_user:
    value: 'admin'
    label: 'Foreman username'
    type: "text"
    description:
    weight: 210
    regex:
      source: &letdig_regex '^[A-Za-z0-9]*$'
      error: "Valid option is a sequence of letters and digits"

  foreman_password:
    value: 'changeme'
    label: 'Foreman password'
    type: "text"
    description:
    weight: 220
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"

  deploy_user:    # disabled until getting some clarification from Scott
    value: 'deploy_user'
    label: 'Operator username'
    type: "text"
    description:
    weight: 230
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"
    restrictions:
      - condition: "true" 
        action: "disable"

  deploy_password: # disabled until getting some clarification from Scott
    value: 'deploy_password'
    label: 'Operator password'
    type: "text"
    description:
    weight: 240
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"
    restrictions:
      - condition: "true" 
        action: "disable"

  oauth_consumer_key:
    value: 'WvZpMupBEGZPj6RXXZBprvUKg6kSNM5e'
    label: 'Oauth consumer key'
    type: "text"
    description: |
      Oauth key and secret values for the Foreman instance
      Leave it blank to get random ones.
    weight: 250
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"

  oauth_consumer_secret:
    value: 'EiwMYSN78wKxQETrqB7rhCWBn9HcXV3x'
    label: 'Oauth consumer secret'
    type: "text"
    description: |
      You can retrieve it later from
      Foreman Administer > Settings > Auth
    weight: 260
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"

  own_ssl_certificate: # Checkbox
    description:
    label: "Use custom certificates on LCM nodes."
    type: "checkbox"
    value: false
    weight: 265

  ssl_ca_location:
    value: "" 
    label: "SSL CA location"
    type: "text"
    description: |
      Provide path to custom SSL CA. 
      Ex: /var/lib/puppet/ssl/certs/ca.pem
    weight: 270
    restrictions:
      - condition: "settings:fuel-plugin-lcm.own_ssl_certificate.value != true"
        action: "disable"
    regex:
      source: &file_path '^(/[-A-Za-z0-9_./]*|^)$'
      error: "Non valid option. Wrong symbol."

  ssl_cert_location:
    value: ""
    label: "SSL CERT location"
    type: "text"
    description: |
      Provide path to custom SSL CERT. 
      Ex: /var/lib/puppet/ssl/certs/fuel.domain.tld.pem
    weight: 280
    restrictions:
      - condition: "settings:fuel-plugin-lcm.own_ssl_certificate.value != true"
        action: "disable"
    regex:
      source: *file_path
      error: "Non valid option. Wrong symbol."

  ssl_crl_location:
    value: ""
    label: "SSL CRL location"
    type: "text"
    description: | 
      Provide path to custom SSL CRL. 
      Ex.: /var/lib/puppet/ssl/crl.pem
    weight: 290
    restrictions:
      - condition: "settings:fuel-plugin-lcm.own_ssl_certificate.value != true"
        action: "disable"
    regex:
      source: *file_path
      error: "Non valid option. Wrong symbol."


  db_user:
    value: 'foreman'
    label: "DB username"
    type: "text"
    description: "Database 'production' user"
    weight: 300
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters"

  db_pass:
    value: 'changeme' 
    label: "DB password"
    type: "text"
    description: "Database 'production' password"
    weight: 310
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters"

  own_puppet_certificate: # Checkbox
    description:
    label: "Use custom puppet certificates on LCM nodes."
    type: "checkbox"
    value: false
    weight: 350

  puppet_ssl_ca_location:
    value: ''
    label: "Puppet ssl ca location"
    type: "text"
    description: |
      Provide path to custom SSL CA. 
      Ex: /var/lib/puppet/ssl/certs/ca.pem
    weight: 360
    restrictions:
      - condition: "settings:fuel-plugin-lcm.own_puppet_certificate.value != true"
        action: "disable"
    regex:
      source: *file_path
      error: "Non valid option. Wrong symbol."

  puppet_ssl_cert:
    value: ''
    label: "Puppet ssl cert"
    type: "text"
    description: |
      Provide path to custom SSL CERT. 
      Ex: /var/lib/puppet/ssl/certs/fuel.domain.tld.pem
    weight: 370
    restrictions:
      - condition: "settings:fuel-plugin-lcm.own_puppet_certificate.value != true"
        action: "disable"
    regex:
      source: *file_path
      error: "Non valid option. Wrong symbol."

  puppet_ssl_key:
    value: ''
    label: "Puppet ssl key"
    type: "text"
    description: |
      Provide path to custom SSL KEY. 
      Ex: /var/lib/puppet/ssl/private_keys/fuel.domain.tld.pem
    weight: 380
    restrictions:
      - condition: "settings:fuel-plugin-lcm.own_puppet_certificate.value != true"
        action: "disable"
    regex:
      source:  *file_path
      error: "Non valid option. Wrong symbol."

  foreman_base_url:
    value: ""
    label: "Foreman base url"
    type: "text"
    description: |
      Smart proxy needs to know where Foreman API lives.
      https://smart-proxy-FQDN by default
    weight: 390
    regex:
      source: *url_regex
      error: "Invalid URL"

  oauth_effective_user:
    value: "admin"
    label: "Oauth effective user"
    type: "text"
    description: "User to be used for REST interaction"
    weight: 400
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"
  
  tftp:  # (boolean to turn on tftp or not)
    description:  
    label: "Use foreman TFTP"
    type: "checkbox"
    value: false
    weight: 420
  dhcp:  # (boolean for dhcp)
    description: 
    label: "Use foreman DHCP"
    type: "checkbox"
    value: false
    weight: 430
  dns:   # (boolean for dns)
    description: 
    label: "Use foreman DNS"
    type: "checkbox"
    value: false
    weight: 440
  bmc:   # (boolean for IPMI plugin)
    description: 
    label: "Use foreman IPMI plugin"
    type: "checkbox"
    value: false
    weight: 450

