attributes:
  metadata:
    perconadb_check_password:
      generator: "password"
    keepalived_psk:
      generator: "password"
    foreman_db_password:
      generator: "password"
    configdb_tenant: "services"

#Keystone password for configdb user
  configdb_pass:
    label: "Keystone password for configdb user"
    description: "User created in fuel master node by command: openstack --os-username=admin --os-auth-url=http://127.0.0.1:35357/v2.0 --os-project-name=admin --os-password=<admin password> user create --project services --password <your password> --enable <your user>"
    type: "password"
    value: "ChangeMe"
    weight: 10
    restrictions: &hide
      - condition: "settings:fuel-plugin-lcm.metadata.enabled != true"
        action: hide

  configdb_user:
    label: "Keystone user for configdb"
    description: "User created in fuel master node by command: openstack --os-username=admin --os-auth-url=http://127.0.0.1:35357/v2.0 --os-project-name=admin --os-password=<admin password> user create --project services --password <your password> --enable <your user>"
    type: "text"
    value: "configdb"
    weight: 5
    restrictions: *hide

# Keepalived
  public_vip_enabled:
    description: "Enable public vip reservation for LCM webui"
    label: "Enable public VIP"
    type: "checkbox"
    value: false
    weight: 40

# Puppet Master
  server_foreman_url:
    label: "Foreman URL"
    description: "Custom URL for the Foreman installation. By default used Puppet master FQDN. Example: https://foreman.com"
    type: "text"
    regex:
      source: &url_regex '^(?:[hH][tT][tT][pP](?:[sS])?:\/\/)(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$|^$'
      error: "Invalid URL"
    value: ""
    weight: 120
    restrictions: *hide

# R10k:
  private_repo:
    description: "Switch ON if R10k control repo is private."
    label: "Configure private repo user"
    type: "checkbox"
    value: false
    weight: 125
    restrictions: *hide
  r10k_key:
    description: "Please supply private key for R10k to access a private repo over SSH."
    label: "Private repo key"
    type: "file"
    value: ''
    weight: 130
    restrictions: &private_repo_hide
      - condition: "settings:fuel-plugin-lcm.private_repo.value != true or settings:fuel-plugin-lcm.metadata.enabled != true"
        action: hide
  user:
    description: "Please supply R10k username to access a private repo over SSH."
    label: "R10k repo SSH user"
    type: "text"
    value: "puppetr10k"
    weight: 131
    restrictions: *private_repo_hide
  mode:
    description: "Please supply mode for R10k files"
    label: "R10k privileges mode"
    type: "text"
    value: "0755"
    weight: 132
    restrictions: *private_repo_hide
  r10k_do_init:
    description: "If r10k should create puppet env after deployment"
    label: "Create puppet env"
    type: "checkbox"
    value: false
    weight: 135
    restrictions: *hide
  remote_repo:
    description: "Please supply control repo link for R10k"
    label: "R10k control repo link"
    type: "text"
    value: 'http://172.18.194.28:8082/root/lcm_control.git'
    weight: 155
    regex:
      source: &non_empty_string '\S'
      error: "Control repository link is a mandatory field"
    restrictions: *hide

# R10k Webhook:
  port:
    description: "Please supply port number for Middlware"
    label: "Middleware Http port"
    type: "text"
    value: "9292"
    weight: 165
    restrictions: *hide
  webhook_auth_user:
    description: "All webhook related files will belong to this user"
    label: "Application owner account"
    type: "text"
    value: "r10kwebhook"
    weight: 170
    restrictions: *hide

# Foreman
  ##### Source document from Scott:  https://gist.github.com/sbrimhall/79997bd90c7e5eca9e2f
  foreman_user:
    value: 'admin'
    label: 'Foreman username'
    type: "text"
    description:
    weight: 210
    regex:
      source: &letdig_regex '^[A-Za-z0-9]*$'
      error: "Valid option is a sequence of letters and digits"
    restrictions: *hide
  foreman_password:
    value:
      generator: 'password'
    label: 'Foreman password'
    type: "password"
    description:
    weight: 220
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"
    restrictions: *hide
  perconadb_root_password:
    value:
      generator: 'password'
    label: 'PerconaDB root password'
    type: "password"
    description:
    weight: 230
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"
    restrictions:
      - condition: "settings:fuel-plugin-lcm.metadata.enabled"
        action: hide
  oauth_consumer_key:
    value:
      generator: 'password'
      generator_arg: '32'
    label: 'Oauth consumer key'
    type: "password"
    description: |
      Oauth key and secret values for the Foreman instance
      Leave it blank to get random ones.
    weight: 250
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"
    restrictions: *hide
  oauth_consumer_secret:
    value:
      generator: 'password'
      generator_arg: '32'
    label: 'Oauth consumer secret'
    type: "password"
    description: |
      You can retrieve it later from
      Foreman Administer > Settings > Auth
    weight: 260
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"
    restrictions: *hide
  own_ssl_certificate:
    description:
    label: "Use custom certificates on LCM nodes."
    type: "checkbox"
    value: false
    weight: 265
    restrictions: *hide
  ssl_foreman_cert_private_key:
    value: ""
    label: 'SSL CERT private key'
    type: "file"
    description: |
      Load a custom SSL CERT private key here  and
      an appropriate certificate in the next field
    weight: 275
    restrictions: &own_ssl_certificate_hide
      - condition: "settings:fuel-plugin-lcm.own_ssl_certificate.value != true or settings:fuel-plugin-lcm.metadata.enabled != true"
        action: "hide"
  ssl_foreman_cert:
    value: ""
    label: "SSL CERTIFICATE"
    type: "file"
    description: |
      Load signed Foreman SSL certificate, also
      please load the private key in the prev field
    weight: 280
    restrictions: *own_ssl_certificate_hide
  ssl_crl_location:
    value: ""
    label: "SSL CRL file"
    type: "file"
    description: |
      Load custom SSL CRL
    weight: 290
    restrictions: *own_ssl_certificate_hide
  own_puppet_certificate:
    description:
    label: "Use custom puppet certificates on LCM nodes."
    type: "checkbox"
    value: false
    weight: 350
    restrictions:
      - condition: "true != false" # Until the necessity of the Puppet CA will be discussed with Scott
        action: hide
  puppet_ssl_ca_location:
    value: ''
    label: "Puppet ssl ca location"
    type: "text"
    description: |
      Provide path to custom SSL CA.
      Ex: /var/lib/puppet/ssl/certs/ca.pem
    weight: 360
    restrictions: &own_puppet_certificate_hide
      - condition: "settings:fuel-plugin-lcm.own_puppet_certificate.value != true or settings:fuel-plugin-lcm.metadata.enabled != true"
        action: "hide"
    regex:
      source: &file_path '^(/[-A-Za-z0-9_./]*|^)$'
      error: "Non valid option. Wrong symbol."
  puppet_ssl_cert:
    value: ''
    label: "Puppet ssl cert"
    type: "text"
    description: |
      Provide path to custom SSL CERT.
      Ex: /var/lib/puppet/ssl/certs/fuel.domain.tld.pem
    weight: 370
    restrictions: *own_puppet_certificate_hide
    regex:
      source: *file_path
      error: "Non valid option. Wrong symbol."
  puppet_ssl_key:
    value: ''
    label: "Puppet ssl key"
    type: "text"
    description: |
      Provide path to custom SSL KEY.
      Ex: /var/lib/puppet/ssl/private_keys/fuel.domain.tld.pem
    weight: 380
    restrictions: *own_puppet_certificate_hide
    regex:
      source:  *file_path
      error: "Non valid option. Wrong symbol."
  foreman_base_url:
    value: ""
    label: "Foreman base url"
    type: "text"
    description: |
      Smart proxy needs to know where Foreman API lives.
      https://smart-proxy-FQDN by default
    weight: 390
    regex:
      source: *url_regex
      error: "Invalid URL"
    restrictions: *hide
  oauth_effective_user:
    value: "admin"
    label: "Oauth effective user"
    type: "text"
    description: "User to be used for REST interaction"
    weight: 400
    regex:
      source: *letdig_regex
      error: "Valid option is a sequence of letters and digits"
    restrictions: *hide
  tftp:
    description:
    label: "Use foreman TFTP"
    type: "checkbox"
    value: false
    weight: 420
    restrictions: *hide
  dhcp:
    description:
    label: "Use foreman DHCP"
    type: "checkbox"
    value: false
    weight: 430
    restrictions: *hide
  dns:
    description:
    label: "Use foreman DNS"
    type: "checkbox"
    value: false
    weight: 440
    restrictions: *hide
  bmc:
    description:
    label: "Use foreman IPMI plugin"
    type: "checkbox"
    value: false
    weight: 450
    restrictions: *hide
